### ISSUE TITLE
How to handle 'null' data (aka tilde ~ )?

### ISSUE THREAD

**Issue by taurus-forever** [eserte/p5-Kwalify#1]
Hi,

I am trying to use your tool to validate schema of our YAML files,
but noticed a problem which I cannot solve.

We have a lot of places where we define some options without values,
as described in YAML spec: http://yaml.org/spec/history/2002-04-07.html#trans-null
which later can be exposed in sequences, like:

```
> cat /tmp/config.yml

---
foo:
  bar: ~

> cat /tmp/schema.yml 
name: test
desc: test for tilde
type: map
mapping:

 "foo":
    type: map
    required: yes
    mapping:
     "bar":
        required: no
        type: seq
        sequence:
          - { type: str, required: no }

> pkwalify -f /tmp/schema.yml /tmp/config.yml 
Use of uninitialized value $data in concatenation (.) or string at /usr/share/perl5/Kwalify.pm line 275.
/tmp/config.yml#0: INVALID
  - [/foo/bar] Non-valid data , expected sequence
```

I have carefully checked http://www.kuwata-lab.com/kwalify/ruby/users-guide.01.html  and found:

> required:  Value is required when true (default is false). This is similar to not-null constraint in RDBMS.

Does it mean that "~" (tilde) (aka null value) should be thread as valid value for a sequence?
What is the proper way to thread such kind of YAML configs from your point of view?

BTW, thank you for Perl implementation of Kwalify!

**Comment by eserte** [comment]
The ruby kwalify passes your example, so I think the perl implementation should, too. I think I'll should have a fix out soon...

**Comment by eserte** [comment]
You can try the latest github commits; this should address your issue.

**Comment by taurus-forever** [comment]
First of all thank you for super quick fix!
The code works as expected, the warning has gone, but I suppose I didn't cover one corner case in the example above.
Lets assume we need to be sure that  foo->bar exist, in this case we should use:

```
cat /tmp/config.yml
---
foo:
  bar: ~

> cat /tmp/schema.yml 
name: test
desc: test for tilde
type: map
mapping:

 "foo":
    type: map
    required: yes
    mapping:
     "bar":
        required: yes
        type: seq
        sequence:
          - { type: str, required: no }

> pkwalify -f /tmp/schema.yml /tmp/config.yml
 /tmp/config.yml#0: INVALID
  - [/foo] Expected required key 'bar'
  - [/foo/bar] Unexpected key 'bar'
```

Note "required: yes" for "bar". The result looks strange :-( while kwalify is valid and should be success as for me. What do you think?

**Comment by eserte** [comment]
Are you objecting the somewhat contradicting error message? I can change this to

```
/tmp/config.yml#0: INVALID
  - [/foo] Expected required key 'bar'
  - [/foo/bar] Value required but got undef
```

which is close what I got with ruby kwalify 0.7.2:

```
/tmp/config.yml#0: INVALID
  - [/foo] key 'bar:' is required.
  - [/foo/bar] value required but none.
```

**Comment by taurus-forever** [comment]
Probably I have to address current issue to kwalify then (is it still supported?). 
I am not worried about error message itself, my problem that I have no possibility to validate situation:

```
cat /tmp/config.yml
---
foo:
  bar: ~
```

where "foo" and "bar" are mandatory options for the YML config, while 'bar' values are optional.

Real life sample:

```
cat /etc/my_config.yml
---
my_server:
  whitelisted_ips: ~
```

and client can define IPs he wants to thread somehow as:

```
cat /etc/my_config.yml
---
my_server:
  whitelisted_ips:
    - 1.1.1.1
    - 2.2.2.2
```

If I define validation schema as:

```

 "foo":
    type: map
    required: yes
    mapping:
     "bar":
        required: yes
        type: seq
        sequence:
          - { type: any, required: no }
```

I got error like you displayed above. So, I have to use "required: no" for "bar". It pass validation well in this case, but user can delete "whitelisted_ips" from /etc/my_config.yml and validation will NOT notice it :-( meh.

Other option is define schema as:

```
---
my_server:
  whitelisted_ips: []
```

instead of "tilde" in this case I can use  "bar->required: yes" and all works as expected.
But it requires changes/verification of tons Perl code to be sure that code threads "tilde" (NULL) in the same way as "[]" (empty array). Which is identical from schema validation point of view (as for me). 

As soon as we define sequence as " - { type: any, required: no }"  it should match empty array as well as null. 

What do you think, should I try to contact kwalify team?

**Comment by taurus-forever** [comment]
Slaven, your comments about the issue above are appreciate.
We can prepare pull request which can support "tilde" for pkwalify library (controlled by init option and disabled by default). Will you accept it for merging? Tnx in advance!

**Comment by taurus-forever** [comment]
JFYI, we have decided to change our YML schema and
use strict values definition (use empty array "[]" instead of tilde "~").
Resolving the issue. Thank you for the fix!
