### ISSUE TITLE
[PATCH] fix lintian errors on pod2man

### ISSUE THREAD

**Issue by gregoa** [eserte/p5-Kwalify#2]
In Debian we are currently applying the following patch to
p5-Kwalify.
We thought you might be interested in it too.

```
Subject: fix lintian errors on pod2man
Origin: vendor
From: Victor Seva <linuxmaniac@torreviejawireless.org>
Last-Update: 2015-08-13
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/pkwalify.git/plain/debian/patches/fix_manpages.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by eserte** [comment]
Thanks, but I don't understand some things in the proposed patch:
- the added =encoding directive in Kwalify.pm seems unnecessary to me --- there's no literal latin2 text in this Pod, just an escaped unicode codepoint which just happens to appear in the latin2 charset, but encoding directives are not necessary for escaped characters
- why the moved =encoding directives in Schema/Kwalify.pm and pkwalify? perlpodspec says that this directive "should occur early in the document". At least it makes the diff unnecessary big

**Comment by gregoa** [comment]
On Thu, 13 Aug 2015 13:30:28 -0700, Slaven Rezić wrote:

Hi,

and thanks for your quick reply.
I've forwarded your question to the original author of the patch as
well who might be better suited to answer.

Cheers,
gregor

## 

 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
`. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
`\-

**Comment by linuxmaniac** [comment]
> the added =encoding directive in Kwalify.pm seems unnecessary to me
> why the moved =encoding directives in Schema/Kwalify.pm and pkwalify?

You're quite right, my rockie mistake. Patch updated.

**Comment by eserte** [comment]
OK. I have a slightly different patch already committed.
